apiVersion: zalando.org/v1
kind: PlatformCredentialsSet
metadata:
  name: prometheus-credentials
  namespace: kube-system
spec:
  application: prometheus
  token_version: v2
  tokens:
    remote-write: {}
